package io.github.darkryh.katalyst.testing.core.schemapolicy

import io.github.darkryh.katalyst.config.DatabaseConfig
import io.github.darkryh.katalyst.di.config.SchemaPolicy
import io.github.darkryh.katalyst.testing.core.KatalystTestEnvironment
import io.github.darkryh.katalyst.testing.core.katalystTestEnvironment
import java.sql.DriverManager
import java.util.UUID
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Pins the observable difference between the schema policies.
 *
 * CREATE_MISSING and CREATE_MISSING_AND_VALIDATE share the same creation step, so on a fresh
 * database they are indistinguishable. They diverge only against an EXISTING table whose shape
 * has drifted from the Kotlin definition: table creation never alters a table that already
 * exists, so the drift survives it. CREATE_MISSING tolerates that silently;
 * CREATE_MISSING_AND_VALIDATE reports the pending statements and, with the default
 * failOnPendingStatements = true, aborts boot.
 *
 * That default is worth pinning: the SchemaPolicy KDoc describes
 * CREATE_MISSING_AND_VALIDATE as logging pending statements, directly after describing VALIDATE
 * as failing startup. Read together that implies this policy is the non-fatal variant. It is not
 * - both share one flag and both abort by default.
 */
class SchemaPolicyBehaviourTest {

    private var environment: KatalystTestEnvironment? = null
    private lateinit var jdbcUrl: String

    @AfterTest
    fun tearDown() {
        environment?.close()
        environment = null
    }

    /**
     * Pre-creates `policy_widgets` WITHOUT the `name` column that [PolicyWidgetsTable] declares,
     * so the schema is already drifted before boot.
     */
    private fun databaseWithDriftedTable(): DatabaseConfig {
        jdbcUrl = "jdbc:h2:mem:katalyst-policy-${UUID.randomUUID()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
        DriverManager.getConnection(jdbcUrl, "sa", "").use { connection ->
            connection.createStatement()
                .execute(
                    "CREATE TABLE policy_widgets " +
                        "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)"
                )
        }
        return DatabaseConfig(url = jdbcUrl, driver = "org.h2.Driver", username = "sa", password = "")
    }

    private fun boot(config: DatabaseConfig, policy: SchemaPolicy): Result<KatalystTestEnvironment> =
        runCatching {
            katalystTestEnvironment {
                database(config)
                scan("io.github.darkryh.katalyst.testing.core.schemapolicy")
                schema(policy)
                disableScheduler()
            }.also { environment = it }
        }

    @Test
    fun `createMissing tolerates a drifted existing table`() {
        val result = boot(databaseWithDriftedTable(), SchemaPolicy.CREATE_MISSING)

        assertTrue(
            result.isSuccess,
            "CREATE_MISSING should boot: it only creates absent tables and never inspects " +
                "the shape of one that already exists"
        )
    }

    @Test
    fun `createMissingAndValidate aborts boot on a drifted existing table`() {
        val result = boot(databaseWithDriftedTable(), SchemaPolicy.CREATE_MISSING_AND_VALIDATE)

        assertTrue(
            result.isFailure,
            "CREATE_MISSING_AND_VALIDATE must abort boot on pending statements with the default " +
                "failOnPendingStatements = true - despite KDoc that reads as if it only logs"
        )
        // The diagnostic can sit on a cause rather than the top-level failure, so walk the chain.
        val messages = generateSequence(result.exceptionOrNull()) { it.cause }
            .mapNotNull { it.message }
            .toList()
        assertTrue(
            messages.any { it.contains("pending migration statement") },
            "expected the pending-statements diagnostic somewhere in the cause chain, got: $messages"
        )
    }

    @Test
    fun `validate aborts boot on a drifted existing table`() {
        val result = boot(databaseWithDriftedTable(), SchemaPolicy.VALIDATE)

        assertTrue(result.isFailure, "VALIDATE must abort boot on pending statements")
    }

    @Test
    fun `none ignores drift entirely`() {
        val result = boot(databaseWithDriftedTable(), SchemaPolicy.NONE)

        assertTrue(result.isSuccess, "NONE must neither create nor inspect the schema")
        assertFalse(
            columnExists("policy_widgets", "NAME"),
            "NONE must not have created or altered anything"
        )
    }

    @Test
    fun `both create policies build the table on a fresh database`() {
        listOf(SchemaPolicy.CREATE_MISSING, SchemaPolicy.CREATE_MISSING_AND_VALIDATE).forEach { policy ->
            jdbcUrl = "jdbc:h2:mem:katalyst-policy-${UUID.randomUUID()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
            val fresh = DatabaseConfig(url = jdbcUrl, driver = "org.h2.Driver", username = "sa", password = "")

            val result = boot(fresh, policy)

            assertTrue(result.isSuccess, "$policy should boot cleanly on a fresh database")
            assertTrue(
                columnExists("policy_widgets", "NAME"),
                "$policy should have created policy_widgets with its declared columns"
            )
            environment?.close()
            environment = null
        }
    }

    /**
     * Identifier case is not portable here — a table created by plain DDL and one created by
     * Exposed can be folded differently — so match case-insensitively rather than guessing.
     */
    private fun columnExists(table: String, column: String): Boolean =
        runCatching {
            DriverManager.getConnection(jdbcUrl, "sa", "").use { connection ->
                connection.metaData.getColumns(null, null, null, null).use { rs ->
                    generateSequence { if (rs.next()) rs else null }.any {
                        it.getString("TABLE_NAME").equals(table, ignoreCase = true) &&
                            it.getString("COLUMN_NAME").equals(column, ignoreCase = true)
                    }
                }
            }
        }.getOrDefault(false)
}
