import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    kotlin("multiplatform") version "2.4.0"
    id("org.jetbrains.compose") version "1.9.3"
    id("org.jetbrains.kotlin.plugin.compose") version "2.4.0"
}

group = "io.github.darkryh.katalyst"
version = "1.0.0-SNAPSHOT"

// Single source of truth for the Katalyst artifact version the generator pins into new projects (and
// shows in the header). Overridden at release time by the Pages workflow (`-PkatalystVersion=<tag>`)
// so the published site tracks whatever release was just cut — alpha, beta, rc or stable. Falls back
// to the current line for local and non-release builds.
val katalystVersion: String =
    (findProperty("katalystVersion") as String?)?.takeIf { it.isNotBlank() } ?: "1.0.0-alpha05"

// Emits BuildInfo.KATALYST_VERSION into commonMain so StarterTemplate reads the injected value.
val generateInitializrBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/initializr/kotlin")
    val version = katalystVersion
    inputs.property("katalystVersion", version)
    outputs.dir(outputDir)
    doLast {
        val file =
            outputDir.get().file("io/github/darkryh/katalyst/initializr/template/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package io.github.darkryh.katalyst.initializr.template

            /** Generated by initializr/build.gradle.kts — do not edit. */
            internal object BuildInfo {
                const val KATALYST_VERSION: String = "$version"
            }
            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    // JVM target exists ONLY so the pure generation logic (model/template/substitution/zip — all in
    // commonMain, no browser APIs) can be unit-tested quickly with kotlin.test via `jvmTest`.
    jvm()

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser {
            commonWebpackConfig {
                outputFileName = "initializr.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateInitializrBuildInfo)
            dependencies {
                // The Compose compiler plugin is applied to every target (incl. the test-only JVM
                // target), so the Compose runtime must be on the common class path even though common
                // code is pure. (Bundled-font resources are wired up with the UI in a later step.)
                implementation(compose.runtime)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        wasmJsMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
        }
    }
}
