package io.github.darkryh.katalyst.testing.core.schemapolicy

import io.github.darkryh.katalyst.config.DatabaseConfig
import io.github.darkryh.katalyst.di.config.SchemaPolicy
import io.github.darkryh.katalyst.testing.core.KatalystTestEnvironment
import io.github.darkryh.katalyst.testing.core.katalystTestEnvironment
import java.sql.DriverManager
import java.util.UUID
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Pins the observable difference between the schema policies.
 *
 * The axis that matters is what each policy does about an EXISTING table whose shape has drifted
 * from the Kotlin definition, because `CREATE TABLE IF NOT EXISTS` skips such a table whole:
 *
 *  - a column the Kotlin table declares and the database lacks is ADDITIVE drift. The creating
 *    policies close it (`ALTER TABLE ... ADD COLUMN`) — that is what `createMissingColumns = true`,
 *    the default, buys. Set it to false and the drift survives creation exactly as it used to.
 *  - a column the database has and Kotlin does not is DESTRUCTIVE drift. No policy touches it, ever:
 *    closing it means dropping data. Only the validating policies report it.
 *
 * That default is worth pinning: the SchemaPolicy KDoc describes CREATE_MISSING_AND_VALIDATE as
 * logging pending statements, directly after describing VALIDATE as failing startup. Read together
 * that implies this policy is the non-fatal variant. It is not — both share one flag and both abort
 * by default.
 */
class SchemaPolicyBehaviourTest {

    private var environment: KatalystTestEnvironment? = null
    private lateinit var jdbcUrl: String

    @AfterTest
    fun tearDown() {
        environment?.close()
        environment = null
    }

    private fun freshDatabase(): DatabaseConfig {
        jdbcUrl = "jdbc:h2:mem:katalyst-policy-${UUID.randomUUID()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
        return DatabaseConfig(url = jdbcUrl, driver = "org.h2.Driver", username = "sa", password = "")
    }

    /**
     * Pre-creates `policy_widgets` WITHOUT the `name` column that [PolicyWidgetsTable] declares, so
     * the live schema is missing a column before boot. Additive drift: a creating policy can close
     * it, because the table is empty and nothing is destroyed by adding the column.
     */
    private fun databaseMissingAColumn(): DatabaseConfig {
        val config = freshDatabase()
        execute(
            "CREATE TABLE policy_widgets " +
                "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)"
        )
        return config
    }

    /**
     * Pre-creates `policy_widgets` with every declared column PLUS an extra one Kotlin knows nothing
     * about. Destructive drift: closing it means `DROP COLUMN`, so no policy may fix it and only the
     * validating ones report it.
     */
    private fun databaseWithAnUnmappedColumn(): DatabaseConfig {
        val config = freshDatabase()
        execute(
            "CREATE TABLE policy_widgets (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(128) NOT NULL, " +
                "legacy_note VARCHAR(64))"
        )
        return config
    }

    private fun execute(sql: String) {
        DriverManager.getConnection(jdbcUrl, "sa", "").use { connection ->
            connection.createStatement().execute(sql)
        }
    }

    private fun boot(
        config: DatabaseConfig,
        policy: SchemaPolicy,
        createMissingColumns: Boolean = true,
    ): Result<KatalystTestEnvironment> =
        runCatching {
            katalystTestEnvironment {
                database(config)
                scan("io.github.darkryh.katalyst.testing.core.schemapolicy")
                schema(policy, createMissingColumns = createMissingColumns)
                disableScheduler()
            }.also { environment = it }
        }

    // ── Additive drift: a column the code declares and the database lacks ──────────────────────

    @Test
    fun `createMissing adds a column an existing table is missing`() {
        val result = boot(databaseMissingAColumn(), SchemaPolicy.CREATE_MISSING)

        assertTrue(result.isSuccess, "CREATE_MISSING should boot: ${result.exceptionOrNull()}")
        assertTrue(
            columnExists("policy_widgets", "NAME"),
            "CREATE_MISSING must add a missing column, not only a missing table — CREATE TABLE IF " +
                "NOT EXISTS skips the existing table whole, so without the ALTER the column would " +
                "only surface as a SQL error on the first query that selected it"
        )
    }

    @Test
    fun `createMissing with createMissingColumns false leaves an existing table alone`() {
        val result = boot(
            databaseMissingAColumn(),
            SchemaPolicy.CREATE_MISSING,
            createMissingColumns = false,
        )

        assertTrue(result.isSuccess, "CREATE_MISSING should still boot: ${result.exceptionOrNull()}")
        assertFalse(
            columnExists("policy_widgets", "NAME"),
            "createMissingColumns = false must restore table-only creation"
        )
    }

    @Test
    fun `createMissingAndValidate adds the missing column and then validates clean`() {
        val result = boot(databaseMissingAColumn(), SchemaPolicy.CREATE_MISSING_AND_VALIDATE)

        assertTrue(
            result.isSuccess,
            "creation closed the whole gap, so validation has nothing left to report: " +
                "${result.exceptionOrNull()}"
        )
        assertTrue(columnExists("policy_widgets", "NAME"))
    }

    @Test
    fun `createMissingAndValidate with createMissingColumns false reports the missing column`() {
        val result = boot(
            databaseMissingAColumn(),
            SchemaPolicy.CREATE_MISSING_AND_VALIDATE,
            createMissingColumns = false,
        )

        assertTrue(
            result.isFailure,
            "with column creation off the drift survives creation and validation must abort boot"
        )
        assertTrue(
            pendingStatementsReported(result),
            "expected the pending-statements diagnostic, got: ${messagesOf(result)}"
        )
    }

    // ── Destructive drift: a column the database has and the code does not ─────────────────────

    @Test
    fun `no policy ever drops a column the code does not declare`() {
        val result = boot(databaseWithAnUnmappedColumn(), SchemaPolicy.CREATE_MISSING)

        assertTrue(result.isSuccess, "CREATE_MISSING tolerates drift it is not allowed to fix")
        assertTrue(
            columnExists("policy_widgets", "LEGACY_NOTE"),
            "creation is strictly additive — dropping an unmapped column would destroy data"
        )
    }

    @Test
    fun `createMissingAndValidate aborts boot on a column the code does not declare`() {
        val result = boot(databaseWithAnUnmappedColumn(), SchemaPolicy.CREATE_MISSING_AND_VALIDATE)

        assertTrue(
            result.isFailure,
            "CREATE_MISSING_AND_VALIDATE must abort boot on pending statements with the default " +
                "failOnPendingStatements = true - despite KDoc that reads as if it only logs"
        )
        assertTrue(
            pendingStatementsReported(result),
            "expected the pending-statements diagnostic, got: ${messagesOf(result)}"
        )
        assertTrue(
            columnExists("policy_widgets", "LEGACY_NOTE"),
            "the policy reports the drop, it never executes it"
        )
    }

    // ── The policies that inspect or touch nothing ────────────────────────────────────────────

    @Test
    fun `validate aborts boot on a drifted existing table`() {
        val result = boot(databaseMissingAColumn(), SchemaPolicy.VALIDATE)

        assertTrue(result.isFailure, "VALIDATE must abort boot on pending statements")
        assertFalse(
            columnExists("policy_widgets", "NAME"),
            "VALIDATE creates nothing, columns included"
        )
    }

    @Test
    fun `none ignores drift entirely`() {
        val result = boot(databaseMissingAColumn(), SchemaPolicy.NONE)

        assertTrue(result.isSuccess, "NONE must neither create nor inspect the schema")
        assertFalse(
            columnExists("policy_widgets", "NAME"),
            "NONE must not have created or altered anything"
        )
    }

    @Test
    fun `both create policies build the table on a fresh database`() {
        listOf(SchemaPolicy.CREATE_MISSING, SchemaPolicy.CREATE_MISSING_AND_VALIDATE).forEach { policy ->
            val fresh = freshDatabase()

            val result = boot(fresh, policy)

            assertTrue(result.isSuccess, "$policy should boot cleanly on a fresh database")
            assertTrue(
                columnExists("policy_widgets", "NAME"),
                "$policy should have created policy_widgets with its declared columns"
            )
            environment?.close()
            environment = null
        }
    }

    /** The diagnostic can sit on a cause rather than the top-level failure, so walk the chain. */
    private fun messagesOf(result: Result<*>): List<String> =
        generateSequence(result.exceptionOrNull()) { it.cause }
            .mapNotNull { it.message }
            .toList()

    private fun pendingStatementsReported(result: Result<*>): Boolean =
        messagesOf(result).any { it.contains("pending migration statement") }

    /**
     * Identifier case is not portable here — a table created by plain DDL and one created by
     * Exposed can be folded differently — so match case-insensitively rather than guessing.
     */
    private fun columnExists(table: String, column: String): Boolean =
        runCatching {
            DriverManager.getConnection(jdbcUrl, "sa", "").use { connection ->
                connection.metaData.getColumns(null, null, null, null).use { rs ->
                    generateSequence { if (rs.next()) rs else null }.any {
                        it.getString("TABLE_NAME").equals(table, ignoreCase = true) &&
                            it.getString("COLUMN_NAME").equals(column, ignoreCase = true)
                    }
                }
            }
        }.getOrDefault(false)
}
