package io.github.darkryh.katalyst.di.error

/**
 * Complete report of all dependency injection validation results.
 *
 * This report is generated by the DependencyValidator during Phase 3 and contains
 * all validation errors found during dependency graph analysis.
 *
 * @param isValid Whether validation passed (no errors)
 * @param errors All validation errors found (empty if valid)
 * @param analysisDurationMs Time taken to analyze dependencies (for diagnostics)
 * @param validationDurationMs Time taken to run all validations (for diagnostics)
 */
data class ValidationReport(
    val isValid: Boolean,
    val errors: List<ValidationError> = emptyList(),
    val analysisDurationMs: Long = 0,
    val validationDurationMs: Long = 0
) {

    /**
     * Count of missing dependency errors.
     */
    val missingDependencyCount: Int
        get() = errors.count { it is MissingDependencyError }

    /**
     * Count of circular dependency errors.
     */
    val circularDependencyCount: Int
        get() = errors.count { it is CircularDependencyError }

    /**
     * Count of uninstantiable type errors.
     */
    val uninstantiableTypeCount: Int
        get() = errors.count { it is UninstantiableTypeError }

    /**
     * Count of well-known property errors.
     */
    val wellKnownPropertyErrorCount: Int
        get() = errors.count { it is WellKnownPropertyError }

    /**
     * Count of secondary type binding errors.
     */
    val secondaryTypeBindingErrorCount: Int
        get() = errors.count { it is SecondaryTypeBindingError }

    /**
     * Count of feature-provided type errors.
     */
    val featureProvidedTypeErrorCount: Int
        get() = errors.count { it is FeatureProvidedTypeError }

    /**
     * Total number of errors found.
     */
    val totalErrorCount: Int
        get() = errors.size

    /**
     * Get a summary of the validation results.
     *
     * @return Summary string describing the validation outcome
     */
    fun getSummary(): String = buildString {
        if (isValid) {
            append("✓ Validation passed")
        } else {
            append("✗ Validation failed with $totalErrorCount error(s)")
            if (missingDependencyCount > 0) append(" - $missingDependencyCount missing")
            if (circularDependencyCount > 0) append(" - $circularDependencyCount cycles")
            if (uninstantiableTypeCount > 0) append(" - $uninstantiableTypeCount uninstantiable")
            if (wellKnownPropertyErrorCount > 0) append(" - $wellKnownPropertyErrorCount properties")
            if (secondaryTypeBindingErrorCount > 0) append(" - $secondaryTypeBindingErrorCount bindings")
            if (featureProvidedTypeErrorCount > 0) append(" - $featureProvidedTypeErrorCount features")
        }
        append(" (analyzed in ${analysisDurationMs}ms, validated in ${validationDurationMs}ms)")
    }
}
