plugins {
    id("io.github.darkryh.katalyst.conventions.common")
}

dependencies {
    // The shared wire contract.
    implementation(projects.katalystTelemetryModel)

    // Serialization runtime for the transport (model serializers are generated in -model).
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.slf4j.api)

    // Framework modules whose already-computed state the capturers tap (union of all capturer
    // moduleDeps), plus katalyst-di for the KatalystFeature contract.
    implementation(projects.katalystCore)
    implementation(projects.katalystDi)
    implementation(projects.katalystPersistence)
    implementation(projects.katalystTransactions)
    implementation(projects.katalystMigrations)
    implementation(projects.katalystEvents)
    implementation(projects.katalystEventsBus)
    implementation(projects.katalystKtor)
    implementation(projects.katalystScheduler)

    // Transport: loopback CIO server with WebSockets. ktor-server-core is also required by the
    // HttpCapturer (di declares ktor via implementation, not api, so it is not transitive).
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.cio)
    implementation(libs.ktor.server.web.sockets)

    testImplementation(libs.kotlinx.coroutines.test)
}

// Emits BuildInfo.KATALYST_VERSION so the telemetry version stamp is derived from the build rather
// than hand-maintained. The constant it replaces carried a "kept in sync with gradle.properties"
// comment while sitting nine releases stale, which meant every telemetry snapshot reported a version
// the running framework was not. Generation removes the drift instead of correcting it once.
val generateTelemetryBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/telemetry/kotlin")
    val katalystVersion = project.version.toString()
    inputs.property("katalystVersion", katalystVersion)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("io/github/darkryh/katalyst/telemetry/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package io.github.darkryh.katalyst.telemetry

            /** Generated by katalyst-telemetry/build.gradle.kts — do not edit. */
            internal object BuildInfo {
                const val KATALYST_VERSION: String = "$katalystVersion"
            }
            """.trimIndent() + "\n",
        )
    }
}

sourceSets.main {
    kotlin.srcDir(generateTelemetryBuildInfo)
}

// Per-module coverage floor (ratchet — raise as coverage grows; never lower). See TESTING_STRATEGY.md.
kover {
    reports {
        verify {
            rule {
                minBound(0)
            }
        }
    }
}
